### ISSUE TITLE
Documentation - example usage

### ISSUE THREAD

**Issue by ericelliott** [transmute-industries/PROPOSAL-OpenPgpSignature2019#6]
It might be useful to include example usage in the documentation.

**Comment by OR13** [comment]
@ericelliott Thanks for the suggestion! I've added some examples to the readme, as well as pointers to a project that uses the suite.

https://github.com/transmute-industries/PROPOSAL-OpenPgpSignature2019/commit/de28d3ed9ee281e4c92710fccf65966feb3d96de

If you have any other questions or suggestions, I'm happy to answer.

**Comment by OR13** [comment]
Here is a UI demo of the example usage I added as well: https://github.com/transmute-industries/PROPOSAL-OpenPgpSignature2019#github-did-example

**Comment by ericelliott** [comment]
Looks great. Thanks for your work on this.

**Comment by OR13** [comment]
Revised to v0.2 https://github.com/transmute-industries/PROPOSAL-OpenPgpSignature2019/commit/7810df089d0d3b9e5d3f17a4f4e14405c75a33d3
